### ISSUE TITLE
Feature request: Export filtered results as data frame

### ISSUE THREAD

**Issue by rpodcast** [RhoInc/CRANsearcher#10]
I think the ability to export a data frame in the workspace that corresponds to the filtered results would be a welcome feature.  Often times I will use the add-in to explore what packages are related to a certain technique or field, and want to save a record of the results so I can discuss further with colleagues or do some additional analysis of the packages identified.  I'd be glad to submit a PR if this sounds like a worthwhile feature to you.

**Comment by bzkrouse** [comment]
@thercast Thank you for your ongoing support of this package! This is a great idea and would be a very useful addition to the app.  We have some ideas of how we might implement this, but if you have an easy solution we certainly welcome your PR.

**Comment by bzkrouse** [comment]
Added to v1.1.0
