### ISSUE TITLE
Redundant CRAN dates with multiple search terms

### ISSUE THREAD

**Issue by rgayler** [RhoInc/CRANsearcher#16]
When you use multiple search terms (say X, Y, and Z) the search summary at the bottom of the CRANsearcher pane will say something like:

**There are n1 packages related to 'X' on CRAN (as of 09/23/17). There are n2 packages related to 'Y' on CRAN (as of 09/23/17). There are n3 packages related to 'Z' on CRAN (as of 09/23/17).**

Presumably CRAN is accessed for all search terms on the same date, so it is redundant to repeat the date for each search term. How about reordering to something like:

**On CRAN at 09/23/17, there are: n1 packages related to 'X'; n2 packages related to 'Y'; n3 packages related to 'Z'.**

**Comment by bzkrouse** [comment]
Thank you for filing this issue and providing such a nice description of the problem. This is a bug with CRANsearcher.  The message is meant to refer to the intersection of search terms and should read:

"There are n packages related to 'X, Y' on CRAN (as of 2017-09-23)."

We will be fixing this shortly!
