### ISSUE TITLE
date format for CRAN as of date

### ISSUE THREAD

**Issue by rgayler** [RhoInc/CRANsearcher#9]
Please change the date format for the CRAN "as of" date at the bottom of the CRANsearcher dialogue to ISO (matching the format of the last release dates. The current format is only used in one country in the world.

Thanks (and CRANsearcher is great!)

**Comment by bzkrouse** [comment]
@rgayler Thank you for the suggestion - we can change this in our next release.  Glad you are enjoying CRANsearcher!

**Comment by bzkrouse** [comment]
Date format [fixed](https://github.com/RhoInc/CRANsearcher/commit/999644c39923b60388225a5f52df38539cb82991#diff-8774201b9d57a06b3254f2cf054a9404) and included in v1.1.0
